
export const VALID_PROVINCES = {
    "Krabi": "Krabi",
    "Kanchanaburi": "Kanchanaburi",
    "Kalasin": "Kalasin",
    "Kamphaeng Phet": "Kamphaeng Phet",
    "Khon Kaen": "Khon Kaen",
    "Chanthaburi": "Chanthaburi",
    "Chachoengsao": "Chachoengsao",
    "Chon Buri": "ChonBuri",
    "Chaiyaphum": "Chaiyaphum",
    "Chumphon": "Chumphon",
    "Chiang Rai": "Chiang Rai",
    "Chiang Mai": "Chiang Mai",
    "Trang": "Trang",
    "Trat": "Trat",
    "Tak": "Tak",
    "Nakhon Nayok": "Nakhon Nayok",
    "Nakhon Pathom": "Nakhon Pathom",
    "Nakhon Phanom": "Nakhon Phanom",
    "Nakhon Ratchasima": "Nakhon Ratchasima",
    "Nakhon Si Thammarat": "Nakhon Si Thammarat",
    "Nakhon Sawan": "Nakhon Sawan",
    "Nonthaburi": "Nonthaburi",
    "Narathiwat": "Narathiwat",
    "Nan": "Nan",
    "Bueng Kan": "Bueng Kan",
    "Buriram": "Buriram",
    "Pathum Thani": "Pathum Thani",
    "Prachuap Khiri Khan": "Prachuap Khiri Khan",
    "Prachinburi": "Prachinburi",
    "Pattani": "Pattani",
    "Phra Nakhon Si Ayutthaya": "Phra Nakhon Si Ayutthaya",
    "Phang Nga": "Phang Nga",
    "Phatthalung": "Phatthalung",
    "Phichit": "Phichit",
    "Phitsanulok": "Phitsanulok",
    "Phetchaburi": "Phetchaburi",
    "Phetchabun": "Phetchabun",
    "Phrae": "Phrae",
    "Phuket": "Phuket",
    "Maha Sarakham": "Maha Sarakham",
    "Mukdahan": "Mukdahan",
    "Mae Hong Son": "Mae Hong Son",
    "Yasothon": "Yasothon",
    "Yala": "Yala",
    "Roi Et": "Roi Et",
    "Ranong": "Ranong",
    "Rayong": "Rayong",
    "Ratchaburi": "Ratchaburi",
    "Lop Buri": "LopBuri",
    "Lampang": "Lampang",
    "Lamphun": "Lamphun",
    "Loei": "Loei",
    "Sakon Nakhon": "Sakon Nakhon",
    "Songkhla": "Songkhla",
    "Satun": "Satun",
    "Samut Prakan": "Samut Prakan",
    "Samut Songkhram": "Samut Songkhram",
    "Samut Sakhon": "Samut Sakhon",
    "Sa Kaeo": "Sa Kaeo",
    "Saraburi": "Saraburi",
    "Sing Buri": "Sing Buri",
    "Sukhothai": "Sukhothai",
    "Suphan Buri": "Suphan Buri",
    "Surat Thani": "Surat Thani",
    "Surin": "Surin",
    "Nong Khai": "Nong Khai",
    "Ang Thong": "Ang Thong",
    "Amnat Charoen": "Amnat Charoen",
    "Udon Thani": "Udon Thani",
    "Uttaradit": "Uttaradit",
    "Uthai Thani": "Uthai Thani",
    "Ubon Ratchathani": "Ubon Ratchathani",
    "Bangkok": "Bangkok Metropolis"
};
