
export const PROVINCE_TH_MAP: Record<string, string> = {
    "Krabi": "กระบี่",
    "Kanchanaburi": "กาญจนบุรี",
    "Kalasin": "กาฬสินธุ์",
    "Kamphaeng Phet": "กำแพงเพชร",
    "Khon Kaen": "ขอนแก่น",
    "Chanthaburi": "จันทบุรี",
    "Chachoengsao": "ฉะเชิงเทรา",
    "Chon Buri": "ชลบุรี",
    "Chaiyaphum": "ชัยภูมิ",
    "Chumphon": "ชุมพร",
    "Chiang Rai": "เชียงราย",
    "Chiang Mai": "เชียงใหม่",
    "Trang": "ตรัง",
    "Trat": "ตราด",
    "Tak": "ตาก",
    "Nakhon Nayok": "นครนายก",
    "Nakhon Pathom": "นครปฐม",
    "Nakhon Phanom": "นครพนม",
    "Nakhon Ratchasima": "นครราชสีมา",
    "Nakhon Si Thammarat": "นครศรีธรรมราช",
    "Nakhon Sawan": "นครสวรรค์",
    "Nonthaburi": "นนทบุรี",
    "Narathiwat": "นราธิวาส",
    "Nan": "น่าน",
    "Bueng Kan": "บึงกาฬ",
    "Buriram": "บุรีรัมย์",
    "Pathum Thani": "ปทุมธานี",
    "Prachuap Khiri Khan": "ประจวบคีรีขันธ์",
    "Prachinburi": "ปราจีนบุรี",
    "Pattani": "ปัตตานี",
    "Phra Nakhon Si Ayutthaya": "พระนครศรีอยุธยา",
    "Phang Nga": "พังงา",
    "Phatthalung": "พัทลุง",
    "Phichit": "พิจิตร",
    "Phitsanulok": "พิษณุโลก",
    "Phetchaburi": "เพชรบุรี",
    "Phetchabun": "เพชรบูรณ์",
    "Phrae": "แพร่",
    "Phuket": "ภูเก็ต",
    "Maha Sarakham": "มหาสารคาม",
    "Mukdahan": "มุกดาหาร",
    "Mae Hong Son": "แม่ฮ่องสอน",
    "Yasothon": "ยโสธร",
    "Yala": "ยะลา",
    "Roi Et": "ร้อยเอ็ด",
    "Ranong": "ระนอง",
    "Rayong": "ระยอง",
    "Ratchaburi": "ราชบุรี",
    "Lop Buri": "ลพบุรี",
    "Lampang": "ลำปาง",
    "Lamphun": "ลำพูน",
    "Loei": "เลย",
    "Sakon Nakhon": "สกลนคร",
    "Songkhla": "สงขลา",
    "Satun": "สตูล",
    "Samut Prakan": "สมุทรปราการ",
    "Samut Songkhram": "สมุทรสงคราม",
    "Samut Sakhon": "สมุทรสาคร",
    "Sa Kaeo": "สระแก้ว",
    "Saraburi": "สระบุรี",
    "Sing Buri": "สิงห์บุรี",
    "Sukhothai": "สุโขทัย",
    "Suphan Buri": "สุพรรณบุรี",
    "Surat Thani": "สุราษฎร์ธานี",
    "Surin": "สุรินทร์",
    "Nong Khai": "หนองคาย",
    "Ang Thong": "อ่างทอง",
    "Amnat Charoen": "อำนาจเจริญ",
    "Udon Thani": "อุดรธานี",
    "Uttaradit": "อุตรดิตถ์",
    "Uthai Thani": "อุทัยธานี",
    "Ubon Ratchathani": "อุบลราชธานี",
    "Bangkok": "กรุงเทพมหานคร"
};
